export default {
  from: "react-use",
  imports: [
    "useBattery",
    "useGeolocation",
    "useHover",
    "useHoverDirty",
    "useHash",
    "useIdle",
    "useIntersection",
    "useKey",
    "useKeyPress",
    "useKeyPressEvent",
    "useLongPress",
    "useMedia",
    "useMediaDevices",
    "useMotion",
    "useMouse",
    "useMouseHovered",
    "useMouseWheel",
    "useNetworkState",
    "useOrientation",
    "usePageLeave",
    "useScratch",
    "useScrolling",
    "useStartTyping",
    "useWindowScroll",
    "useWindowSize",
    "useMeasure",
    "useSize",
    "createBreakpoint",
    "useScrollbarWidth",
    "usePinchZoom",
  ],
};
