export default {
  from: "react-use",
  imports: [
    "createMemo",
    "createReducer",
    "createReducerContext",
    "createStateContext",
    "useDefault",
    "useGetSet",
    "useGetSetState",
    "useLatest",
    "usePrevious",
    "usePreviousDistinct",
    "useRafState",
    "useSetState",
    "useStateList",
    "useToggle",
    "useBoolean",
    "useCounter",
    "useNumber",
    "useList",
    "useMap",
    "useSet",
    "useQueue",
    "useStateValidator",
    "useStateWithHistory",
    "useMultiStateValidator",
    "useMediatedState",
    "useFirstMountState",
    "useRendersCount",
    "createGlobalState",
    "useMethods",
  ],
};
