export default {
  from: "motion/react",
  imports: [
    "AnimateActivity",
    "AnimatePresence",
    "AnimateView",
    "LayoutGroup",
    "LazyMotion",
    "MotionConfig",
    "Reorder",
    "useMotionTemplate",
    "useMotionValueEvent",
    "useScroll",
    "useSpring",
    "useTime",
    "useTransform",
    "useVelocity",
    "useAnimate",
    "useAnimationFrame",
    "useDragControls",
    "useInView",
    "usePageInView",
    "useReducedMotion",
  ],
};
