export default {
  from: "@tanstack/react-router",
  imports: [
    "CatchBoundary",
    "CatchNotFound",
    "ErrorComponent",
    "Navigate",
    "NotFoundComponent",
    "Outlet",
    "createFileRoute",
    "createLazyFileRoute",
    "createRoute",
    "createLazyRoute",
    "createRouteMask",
    "getRouteApi",
    "isNotFound",
    "isRedirect",
    "useAwaited",
    "useBlocker",
    "useCanGoBack",
    "useChildMatches",
    "useLinkProps",
    "useLoaderData",
    "useLoaderDeps",
    "useLocation",
    "useMatch",
    "useMatchRoute",
    "useMatches",
    "useNavigate",
    "useParentMatches",
    "useParams",
    "useRouteContext",
    "useRouter",
    "useRouterState",
    "useSearch",
  ],
};
